cmake_minimum_required(VERSION 3.16)

project(TestSchemaHandler LANGUAGES CXX)

enable_testing()

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Test)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Test)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(TestSchemaHandler tst_schemahandler.h tst_schemahandler.cpp ../src/handlers/schemahandler.cpp ../src/handlers/schemahandler.h

)
add_test(NAME schemahandler COMMAND schemahandler)

target_link_libraries(TestSchemaHandler PRIVATE Qt${QT_VERSION_MAJOR}::Test)

